### ISSUE TITLE
using "*" for service name in bonjour::browse start <service name> <callback> seg faults

### ISSUE THREAD

**Issue by cwjolly** [dongola7/tcl_bonjour#5]
on Linux ( Fedora 14 ) with avahi :
avahi-devel-0.6.27-2.fc14.x86_64
avahi-glib-0.6.27-2.fc14.x86_64
avahi-gobject-0.6.27-2.fc14.x86_64
avahi-autoipd-0.6.27-2.fc14.x86_64
avahi-compat-libdns_sd-0.6.27-2.fc14.x86_64
avahi-0.6.27-2.fc14.x86_64
avahi-tools-0.6.27-2.fc14.x86_64
avahi-compat-libdns_sd-devel-0.6.27-2.fc14.x86_64

followng code segfaults using interactive shell : 

$ /opt/usr8.6b.5/bin/tclsh8.6
% package require bonjour
1.1
% proc chuck { args } {
  puts "$args"
}
%  bounjour::browse start \* chuck
**\* WARNING **\* The program 'tclsh8.6' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=tclsh8.6
Segmentation fault (core dumped)
$

**Comment by dongola7** [comment]
This is due to the fact that passing \* to the bonjour::browse function is not actually valid.  I'll add better error messages and prevent the crash from happening.

I think you're trying to look for all available services using the library.  This is something I'm not currently sure how to do using the dns_sd library itself.

**Comment by dongola7** [comment]
Adding handling of errors in DNSService\* functions.

The library will now return an error when a call to one of the
DNSService\* functions fails.  The error returned is a list consisting
of an error message, the name of the DNSService\* function generating
the error, and the error code (usually a string).

Whenever a background error occurs in a DNSService callback, the error
message will match the format for other functions.

Closed by d68524a0002e65617d9bc0bf5a39f5b4ca4cf030.
